version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - db_net

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    networks:
      - db_net

  python:
    build: 
      context: .
      dockerfile: Dockerfile.python
    command: python ./while_true.py
    volumes:
      - ./python-scripts:/app
    networks:
      - db_net
    depends_on:
      - mysql

networks:
  db_net:
    driver: bridge