version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./data-mysql:/var/lib/mysql
    networks:
      - db_net

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_net

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    networks:
      - db_net
    depends_on:
      - mysql
      - postgres

  python:
    build: 
      context: .
      dockerfile: Dockerfile.python
    command: python ./while_true.py
    volumes:
      - ./python-scripts:/app
    networks:
      - db_net
    depends_on:
      - mysql
      - postgres

networks:
  db_net:
    driver: bridge